### ISSUE TITLE
ValueError: API Key is not validated.

### ISSUE THREAD

**Issue by j3soon** [twcc/TWCC-CLI#34]
**Describe the bug**
After first installation, `twccli config init` with a valid project code results in a "API Key is not validated" error.

**To Reproduce**
1. `pip3 install TWCC-CLI
2. `twccli config init` and enter a valid project code.
3. observe the "API Key is not validated" error.

**Expected behavior**
I expect that after entering the valid project code, a prompt should ask me my API key instead of printing error.

**Screenshots**

![image](https://user-images.githubusercontent.com/20457146/131210308-5ff7bfa9-dd00-4ecc-8539-530a93e9ddd2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - `twccli config version`: `[TWCCLI] This version is 0.5.20`

**Additional context**

This error can be by-passed by `twccli config init -pcode <PROJECT_CODE> --apikey <API_KEY>`. So, I believe that the CLI requires an API key before validating the project code, resulting the error.

The issue may be fixed by:
1. Ask the project key first but do not validate immediately. Then, ask the API key and validate the API key, then validate the project key.
2. Ask the API key first, and then ask the project key. (This is more straightforward)

**Comment by JeanHsuBD** [comment]
Hi there,

Thank you for those suggestion, we will revise the operation process in future release.

You can use `rm -rf ~/.twcc_data` to remove your credential , then create a new API KEY in User Portal and use the new key for TWCC-CLI. (check more informations in [TWCC-doc/TWCC-CLI#APIkey](https://man.twcc.ai/@twccdocs/doc-cli-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-cli-signin-zh#2-API-%E9%87%91%E9%91%B0)

**Comment by JeanHsuBD** [comment]
fixed in v0.5.21, thank you!
