### ISSUE TITLE
twcc-cli login error

### ISSUE THREAD

**Issue by chinf-tw** [twcc/TWCC-CLI#39]
**Describe the bug**
I follow [this document](https://man.twcc.ai/@twccdocs/doc-cli-main-zh/https%3A%2F%2Fman.twcc.ai%2F%40twccdocs%2Fguide-cli-signin-zh) which login twcc-cli but system report a error 
**To Reproduce**
1. using terminal to enter `twccli config init`
2. enter TWCC Project Code
3. enter TWCC APIKEY
4. got a error

**Expected behavior**
I Expected not a error
**Screenshots**
![img](https://i.imgur.com/zuCIIz4.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Browser safari .... but I used twcc-cli

**Additional context**
I think error reason which is difference shell (I use zsh).

**Comment by JeanHsuBD** [comment]
Thank you for raising this issue, while we need some process time, we will schedule this problem solved as soon as possible!

**Comment by twsc-aug** [comment]
quick fix: you can skip this line.
