### ISSUE TITLE
Add version IDs to image names

### ISSUE THREAD

**Issue by yizhou-wang** [twcc/TWCC-CLI#41]
I found it is difficult to find the image for a specific cuda/pytorch version since the images are named only using the created date (e.g., `pytorch-21.08-py3`).

It would be very helpful if you can also include related cuda, pytorch, tensorflow, etc. versions in the names (e.g., `pytorch-21.08-py3-cuda110-pytorch***`). 

Thanks a lot!

**Comment by twsc-aug** [comment]
The reason of using `pytorch-21.08.py3` is according to NGC container image naming rule, so users can use [google search](https://www.google.com/search?client=safari&rls=en&q=NGC+pytorch-21.08.py3&ie=UTF-8&oe=UTF-8) to find out exact software composition of that image.
