### ISSUE TITLE
twccli ls vcs -img command error

### ISSUE THREAD

**Issue by RobinChiu** [twcc/TWCC-CLI#42]
**Describe the bug**
Try to list the image of vcs, but it's fail.

**To Reproduce**
$ twccli ls vcs -img
[TWCC-CLI] Error-40301: You do not have permission to perform this action.

**Expected behavior**
list the available vcs img for creating. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7788730/158360339-7d22ab5f-2e95-4b22-b567-4d5eab22b9d6.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]

**Comment by twsc-aug** [comment]
thanks for reporting this, we will look into this and get back to you soon.
