### ISSUE TITLE
如何透過apache使用shell_exec執行twccli

### ISSUE THREAD

**Issue by pttseng** [twcc/TWCC-CLI#43]
如題
我使用twcc主機內建cli
OS： centos8
以閜為兩個使用情境
1.使用putty執行php code可以透過php shell_exec取得twccli相關資訊=>使用者(centos)
2.相同作法透過http執行同一個php code回傳只有NULL=>使用者(apache)
方式2看起來是因為apache沒有權限使用twccli，請問有其他方法可以解決此問題嗎?

**Comment by JeanHsuBD** [comment]
Please use `sudo python3 -m pip install -U TWCC-CLI`, and check more in our [User Manual](https://man.twcc.ai/@twccdocs/twcc-cli-v05). Hope that will help!

**Comment by pttseng** [comment]
謝謝回覆，問題已自行排除了。
問題及解決方式如下列敘述：
1.這一個問題，我們確實安裝TWCC-CLI。
2.問題的主因在於apache無權限使用python。
3.我嘗試過利用putty登入apache執行相同的php是可以透過TWCCLI取得資料。=>相同方法利用web執行api溝通twccli卻是失敗的。
4.利用putty呼叫php時利用shell_exe("whoami")檢查=>告知我身分是apache使用者。
5.最後的解決方法是透過SELinuxe開放網頁存取python權限，才解決透過web api呼叫twccli取得主機資訊。
